### ISSUE TITLE
Startup advice :)

### ISSUE THREAD

**Issue by drpatelh** [joshsbloom/swabseq#1]
Hi @joshsbloom @sbooeshaghi! Hope you and loved ones are doing well during these difficult times. 

Firstly, I would like to thank you and everyone else involved in the development of this versatile and high-throughput assay. Truly amazing! I am a bioinformatician working at The Francis Crick Institute in London, and our first set of Swab-Seq samples are being sequenced as we speak. I sat down today to collate a list of resources and to bring myself up-to-speed on how to perform the downstream analysis (listed below just in case it benefits anyone else):

[Swab-Seq pre-print](https://www.medrxiv.org/content/10.1101/2020.08.04.20167874v1)

[Swab-Seq GitHub repo - @octantbio](https://github.com/octantbio/SwabSeq)
[Swab-Seq GitHub repo - @joshsbloom](https://github.com/joshsbloom/swabseq)

[Kallisto/bustools pre-print @sbooeshaghi](https://www.medrxiv.org/content/10.1101/2020.05.13.20100131v1)
[Kallisto/bustools pre-print GitHub repo - @pachterlab](https://github.com/pachterlab/BLCSBGLKP_2020)

[Sri Kosuri Talk on 23/07/20](https://hhmi.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=75e70301-cd82-4d06-b6fa-ac0101441082)

[Octant Notion link](https://www.notion.so/Octant-SwabSeq-Testing-9eb80e793d7e46348038aa80a5a901fd)

I should also say that I am one of the core contributors to the [nf-core framework](https://nf-co.re/) and I was recently involved in writing an end-to-end pipeline to perform assembly and intra-host/low-frequency variant calling for viral samples sequenced on the Illumina platform - [nf-core/viralrecon](https://github.com/nf-core/viralrecon).

- Would I be correct in assuming that this repo contains the most up-to-date analysis scripts for Swab-seq?
- Are you using software containers for the analysis? I couldn't see a `Dockerfile` or any other pointers.
- Would this pipeline and the bioinformatics community as a whole benefit from it being added to nf-core? I haven't actually run it from end-to-end and I'd rather not assume anything especially since I have seen some scripts that point to more interactive methods of analysis using Jupyter notebooks / Rstudio 😅

Thanks in advance!

**Comment by joshsbloom** [comment]
Hi Harshil,

We've been using an R-based pipeline at UCLA. Also been working on a conda environment to automate setup of everything except bcl2fastq (see attached files). Will update that on ucla swabseq git repo as soon as I can.

Highly recommend however that you use the kallisto/bustools framework that Sina has developed. It is especially helpful for nextseq/miniseq runs where the per base error rate is higher. It is nicely made and has little dependencies, so not much need for containers there.

Best,
Josh



On 8/27/20 8:16 AM, Harshil Patel wrote:

CAUTION - EXTERNAL EMAIL:Do not click links or open attachments unless you recognize the sender.

Hi @joshsbloom<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_joshsbloom&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=kE7bOsp78YRabuHqW9X3OdoXFJg1NTVkXnEFc2uau90&e=> @sbooeshaghi<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbooeshaghi&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=mYfJcYOoheSRRF5gmBkgXTLwO15VUWK2kFSFGGZNUcg&e=>! Hope you and loved ones are doing well during these difficult times.

Firstly, I would like to thank you and everyone else involved in the development of this versatile and high-throughput assay. Truly amazing! I am a bioinformatician working at The Francis Crick Institute in London, and our first set of Swab-Seq samples are being sequenced as we speak. I sat down today to collate a list of resources and to bring myself up-to-speed on how to perform the downstream analysis (listed below just in case it benefits anyone else):

Swab-Seq pre-print<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.medrxiv.org_content_10.1101_2020.08.04.20167874v1&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=1imxiUNFFq-Yb-CT_81ffsntHMCb5Z2VG1kW58UYZNU&e=>

Swab-Seq GitHub repo - @octantbio<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_octantbio_SwabSeq&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=xlt65iwbWtNczxKeQZP9pCEpw18ysb1D-S_2sLCuc5Y&e=>
Swab-Seq GitHub repo - @joshsbloom<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_joshsbloom_swabseq&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=KqIQaSbS2qn3rj-aS_B42NXgpFi-CwaVUeSU_lLnK4U&e=>

Kallisto/bustools pre-print @sbooeshaghi<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.medrxiv.org_content_10.1101_2020.05.13.20100131v1&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=vhUtClyG9bRf_UhBABr_DoLqEAr6ZKxT_7tUC66Aaes&e=>
Kallisto/bustools pre-print GitHub repo - @pachterlab<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pachterlab_BLCSBGLKP-5F2020&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=eN1aU88kStuNQf4Ihl2Y8tCy0tnp-sfjrqdvGTNBKjQ&e=>

Sri Kosuri Talk on 23/07/20<https://urldefense.proofpoint.com/v2/url?u=https-3A__hhmi.hosted.panopto.com_Panopto_Pages_Viewer.aspx-3Fid-3D75e70301-2Dcd82-2D4d06-2Db6fa-2Dac0101441082&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=NOpRW-MQ-0Nq7Sq6cTj-3pvnH0hYlaX4sbV-Epgn_Vc&e=>

Octant Notion link<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.notion.so_Octant-2DSwabSeq-2DTesting-2D9eb80e793d7e46348038aa80a5a901fd&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=UKF-Zi3R5OYtbb_Veiv2ph8bgP-E5o0lNLoXgUV4uCQ&e=>

I should also say that I am one of the core contributors to the nf-core framework<https://urldefense.proofpoint.com/v2/url?u=https-3A__nf-2Dco.re_&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=5BFKifWEq86n_wAsz2_lf2C-h2MwOmSu59_wdL-2Eh8&e=> and I was recently involved in writing an end-to-end pipeline to perform assembly and intra-host/low-frequency variant calling for viral samples sequenced on the Illumina platform - nf-core/viralrecon<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nf-2Dcore_viralrecon&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=1ht6MzXjCtP9owqkm9Ec6i7X7W4HJmdLp9Fqbnnuono&e=>.

  *   Would I be correct in assuming that this repo contains the most up-to-date analysis scripts for Swab-seq?
  *   Are you using software containers for the analysis? I couldn't see a Dockerfile or any other pointers.
  *   Would this pipeline and the bioinformatics community as a whole benefit from it being added to nf-core? I haven't actually run it from end-to-end and I'd rather not assume anything especially since I have seen some scripts that point to more interactive methods of analysis using Jupyter notebooks / Rstudio 😅

Thanks in advance!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_joshsbloom_swabseq_issues_1&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=YwfWuGRz_0oy0gohLQQMSYb_Bpfmn1oP6emIAb07oC0&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEMYUPN6SFGAEMAEQBBZT6TSCZ2F7ANCNFSM4QNDPCJQ&d=DwMFaQ&c=UXmaowRpu5bLSLEQRunJ2z-YIUZuUoa9Rw_x449Hd_Y&r=L8-RAUDUpAyb0fNSb4_w7vt4L_MZrMlN6wK0EL4LuFU&m=LJvIdNoOry8i-Ke38KaeECXJUJF1zIBghkHf2MSyAXU&s=Lz9iNpRVTmuwiu16mB5bBy20kMadRaV270vpzfFnVO0&e=>.


________________________________

UCLA HEALTH SCIENCES IMPORTANT WARNING: This email (and any attachments) is only intended for the use of the person or entity to which it is addressed, and may contain information that is privileged and confidential. You, the recipient, are obligated to maintain it in a safe, secure and confidential manner. Unauthorized redisclosure or failure to maintain confidentiality may subject you to federal and state penalties. If you are not the intended recipient, please immediately notify us by return email, and delete this message from your computer.

**Comment by drpatelh** [comment]
Thanks a bunch @joshsbloom and apologies for the prompt response! Hope you are well. It turns out we didn't use Swab-seq in-house and I forgot to come back and respond here.
